input {
  tcp {
    port => 5000
    codec => json
  }
  http {
    port => 5001
  }
}

filter {
  if [type] == "gym-activity" {
    mutate {
      add_field => { "[@metadata][target_index]" => "gym-activities-%{+YYYY.MM.dd}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "%{[@metadata][target_index]}"
  }
  stdout {
    codec => rubydebug
  }
}
